exports.SUCCESS_CODE = 0
exports.FAILURE_CODE = 1
exports.UNAUTHORIZED = 403
exports.SERVER_ERROR = 500
exports.NOTFOUND = 404
exports.QUEUE = "messagequeue"
exports.TWILIO_GATEWAY = "twilio"
exports.BULKGATE_GATEWAY = "bulkgate"
exports.SMS_TARIFF = process.env.SMS_TARIFF || 0.06
